### ISSUE TITLE
FI_20639: Trying to load a map (service/layer) from the catalogue always fails

### ISSUE THREAD

**Issue by nicolas-m-brgm** [OneGeology/TechnicalDiscussion#50]
![image](https://user-images.githubusercontent.com/44254759/95872955-b5f20480-0d6f-11eb-845e-1c31c3c94bca.png)
![image](https://user-images.githubusercontent.com/44254759/95872980-bdb1a900-0d6f-11eb-8c25-bfa8e7114617.png)

**Comment by nmtoken** [comment]
Originally https://forge.brgm.fr/issues/20639

Start date: | 26/06/2018

**Comment by nicolas-m-brgm** [comment]
Should we close this issue since we created the #31 ?

**Comment by nmtoken** [comment]
To me it should be open still, because it's currently an either/or situation.  The issue might be resolved by fixing GeoNetwork behaviour,  or upgrading it, or by hiding the tab #31 ).     This GitHub issue has a higher number (50), it is actually the older report  originally 20639 as opposed 23880 for 30. 

If we are saying they are duplicates then the newer one should be closed, not this one

**Comment by nicolas-m-brgm** [comment]
Quick fix : remove map tab from GN
Long term fix : upgrade version of GN

**Comment by Sveouu** [comment]
it does not fail on "every" service.  There are a number of services that work, but probably the only services it works for are the ones that support 1.3.0 GetCapability requests

![image](https://user-images.githubusercontent.com/72437441/145808476-052e4828-3ae7-4b92-a026-65ff3b3cd582.png)

**Comment by nmtoken** [comment]
Portal was upgraded to version 4.n GeoNetwork, and testing against a BGS service (supporting WMS 1.3.0) is (still,  as noted by @Sveouu) working.  Issue may be (have been) related to defaulted versioning by catalogue/portal.

Possibly related to  https://github.com/OneGeology/TechnicalDiscussion/issues/58

Closing now as seems resolved
